# Generated by Django 2.0.6 on 2018-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.CharField(max_length=500, unique=True)),
                ('question_type', models.CharField(max_length=10)),
                ('quetion_options', models.CharField(max_length=200)),
            ],
        ),
    ]
