# Generated by Django 2.0.6 on 2018-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='quetion_options',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
