# Generated by Django 2.0.6 on 2018-06-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0002_auto_20180620_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='quetion_options',
            new_name='question_options',
        ),
    ]
