# Generated by Django 2.0.6 on 2018-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0003_auto_20180620_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHeaders',
            fields=[
                ('header_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('header_text', models.CharField(max_length=100, unique=True)),
                ('header_text_m', models.CharField(max_length=100, unique=True)),
                ('header_remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_text_m',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
