# Generated by Django 2.0.6 on 2018-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0005_auto_20180704_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
