# Generated by Django 2.0.6 on 2018-07-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0006_auto_20180704_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='question_text_m',
        ),
    ]
