# Generated by Django 2.0.6 on 2018-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0007_remove_questionbank_question_text_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='question_text_m',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
