# Generated by Django 2.0.6 on 2018-07-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0008_questionbank_question_text_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='question_text_m',
        ),
    ]
