# Generated by Django 2.0.6 on 2018-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0009_remove_questionbank_question_text_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
