# Generated by Django 2.0.6 on 2018-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0010_auto_20180704_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='question_text_m',
            field=models.CharField(default='Test', max_length=500),
        ),
    ]
