# Generated by Django 2.0.6 on 2018-07-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0011_questionbank_question_text_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_text_m',
            field=models.CharField(max_length=500),
        ),
    ]
