# Generated by Django 2.0.6 on 2018-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0014_remove_questionheader_header_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionheader',
            name='header_remarks',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
