# Generated by Django 2.0.6 on 2018-07-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0015_questionheader_header_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionHeader',
            new_name='QuestionHeaders',
        ),
    ]
