# Generated by Django 2.0.6 on 2018-07-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0016_auto_20180704_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionHeaders',
            new_name='QuestionHeader',
        ),
    ]
