# Generated by Django 2.0.6 on 2018-07-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0017_auto_20180704_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionheader',
            name='header_remarks',
        ),
    ]
