# Generated by Django 2.0.6 on 2018-07-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0018_remove_questionheader_header_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionHeader',
        ),
    ]
