# Generated by Django 2.0.6 on 2018-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0019_delete_questionheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHeader',
            fields=[
                ('header_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('header_text', models.CharField(max_length=100, unique=True)),
                ('header_text_m', models.CharField(max_length=100)),
                ('header_remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
