# Generated by Django 2.0.6 on 2018-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0020_questionheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questionheader',
            name='header_remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
