# Generated by Django 2.0.6 on 2018-08-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbnk', '0021_auto_20180708_2037'),
        ('qbnk', '0021_auto_20180708_1445'),
    ]

    operations = [
    ]
