# Generated by Django 2.0.6 on 2018-08-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_lang',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
