# Generated by Django 2.0.6 on 2018-08-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logn', '0002_profile_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.CharField(blank=True, default='email@email.com', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_mobile',
            field=models.CharField(blank=True, default='0', max_length=25),
        ),
    ]
