# Generated by Django 2.0.6 on 2018-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logn', '0003_auto_20180827_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_office_phone',
            field=models.CharField(blank=True, default='0487 00000000', max_length=25),
        ),
    ]
