# Generated by Django 2.0.6 on 2018-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180703_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_assembly_constituency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_block_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_no_of_female_wards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_no_of_scst_wards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_no_of_wards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_parliamentary_constituency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_taluk_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
