# Generated by Django 2.0.6 on 2018-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180703_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_block_panchayath_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_block_panchayath_wards',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_coastal_line_length_in_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_forest_area_in_hectors',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_jilla_panchayath_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_jilla_panchayath_ward',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_main_roads',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_name_of_rivers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_nearest_railway_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_no_of_rivers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d01_generaldetails',
            name='lsgd_type_of_soil',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
