# Generated by Django 2.0.6 on 2018-07-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180704_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='D03_SexDesegDataofChild',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Male_Child_below_1', models.IntegerField(null=True)),
                ('Female_Child_below_1', models.IntegerField(null=True)),
                ('Male_Child_between1to3', models.IntegerField(null=True)),
                ('Female_Child_between1to3', models.IntegerField(null=True)),
                ('Male_Child_between3to5', models.IntegerField(null=True)),
                ('Female_Child_between3to5', models.IntegerField(null=True)),
                ('Male_Child_between5to6', models.IntegerField(null=True)),
                ('Female_Child_between5to6', models.IntegerField(null=True)),
                ('Male_Child_between6to10', models.IntegerField(null=True)),
                ('Female_Child_between6to10', models.IntegerField(null=True)),
                ('Male_Child_between10to18', models.IntegerField(null=True)),
                ('Female_Child_between10to18', models.IntegerField(null=True)),
            ],
        ),
    ]
