# Generated by Django 2.0.6 on 2018-07-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_d03_sexdesegdataofchild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D03_SexDesegDataofChild',
        ),
    ]
