# Generated by Django 2.0.6 on 2018-08-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180804_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d004',
            name='RBSY_CHIS_t',
        ),
    ]
