# Generated by Django 2.0.6 on 2018-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_d004_rbsy_chis_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='d004',
            name='RBSY_CHIS_t',
            field=models.IntegerField(null=True),
        ),
    ]
