# Generated by Django 2.0.6 on 2018-08-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_d004_rbsy_chis_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d004',
            name='RBSY_CHIS_t',
        ),
    ]
