# Generated by Django 2.0.6 on 2018-08-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_d004_rbsy_chis_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d004',
            name='RBSY_CHIS_F',
        ),
    ]
