# Generated by Django 2.0.6 on 2018-08-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_d004_rbsy_chis_f'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D004',
        ),
    ]
