# Generated by Django 2.0.6 on 2018-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20180804_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='d004',
            name='Multiple_Disability_F',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d004',
            name='RBSY_CHIS_F',
            field=models.IntegerField(null=True),
        ),
    ]
