# Generated by Django 2.0.6 on 2018-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20180806_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='D007',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('S_7_Live_Birth_G', models.IntegerField(null=True)),
                ('S_7_Live_Birth_SC', models.IntegerField(null=True)),
                ('S_7_Live_Birth_ST', models.IntegerField(null=True)),
                ('S_7_Neonatal_Death_0_28day_G', models.IntegerField(null=True)),
                ('S_7_Neonatal_Death_0_28day_SC', models.IntegerField(null=True)),
                ('S_7_Neonatal_Death_0_28day_ST', models.IntegerField(null=True)),
                ('S_7_Infant_Mortality_0_1_G', models.IntegerField(null=True)),
                ('S_7_Infant_Mortality_0_1_SC', models.IntegerField(null=True)),
                ('S_7_Infant_Mortality_0_1_ST', models.IntegerField(null=True)),
                ('S_7_Child_Mortality_1_5_G', models.IntegerField(null=True)),
                ('S_7_Child_Mortality_1_5_SC', models.IntegerField(null=True)),
                ('S_7_Child_Mortality_1_5_ST', models.IntegerField(null=True)),
                ('S_7_Death_5_14_Year_G', models.IntegerField(null=True)),
                ('S_7_Death_5_14_Year_SC', models.IntegerField(null=True)),
                ('S_7_Death_5_14_Year_ST', models.IntegerField(null=True)),
                ('S_7_Death_Above_14_Year_G', models.IntegerField(null=True)),
                ('S_7_Death_Above_14_Year_SC', models.IntegerField(null=True)),
                ('S_7_Death_Above_14_Year_ST', models.IntegerField(null=True)),
                ('S_7_Commited_Suicide_G', models.IntegerField(null=True)),
                ('S_7_Commited_Suicide_SC', models.IntegerField(null=True)),
                ('S_7_Commited_Suicide_ST', models.IntegerField(null=True)),
            ],
        ),
    ]
