# Generated by Django 2.0.6 on 2018-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_d007'),
    ]

    operations = [
        migrations.CreateModel(
            name='D008',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Newborn_measured', models.IntegerField(null=True)),
                ('Newborn_Normal', models.IntegerField(null=True)),
                ('Newborn_Mild', models.IntegerField(null=True)),
                ('Newborn_Moderate', models.IntegerField(null=True)),
                ('Newborn_Severe', models.IntegerField(null=True)),
                ('Under3_measured', models.IntegerField(null=True)),
                ('Under3_Normal', models.IntegerField(null=True)),
                ('Under3_Mild', models.IntegerField(null=True)),
                ('Under3_Moderate', models.IntegerField(null=True)),
                ('Under3_Severe', models.IntegerField(null=True)),
                ('Three_5_measured', models.IntegerField(null=True)),
                ('Three_5_Normal', models.IntegerField(null=True)),
                ('Three_5_Mild', models.IntegerField(null=True)),
                ('Three_5_Moderate', models.IntegerField(null=True)),
                ('Three_5_Severe', models.IntegerField(null=True)),
                ('Adolescent_measured', models.IntegerField(null=True)),
                ('Adolescent_Normal', models.IntegerField(null=True)),
                ('Adolescent_Mild', models.IntegerField(null=True)),
                ('Adolescent_Moderate', models.IntegerField(null=True)),
                ('Adolescent_Severe', models.IntegerField(null=True)),
                ('Pregnant_measured', models.IntegerField(null=True)),
                ('Pregnant_Normal', models.IntegerField(null=True)),
            ],
        ),
    ]
