# Generated by Django 2.0.6 on 2018-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_d008'),
    ]

    operations = [
        migrations.AddField(
            model_name='d008',
            name='Pregnant_Mild',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d008',
            name='Pregnant_Moderate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='d008',
            name='Pregnant_Severe',
            field=models.IntegerField(null=True),
        ),
    ]
