# Generated by Django 2.0.6 on 2018-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_d009'),
    ]

    operations = [
        migrations.CreateModel(
            name='D010',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('LP_School_Govt', models.IntegerField(null=True)),
                ('LP_School_LSG', models.IntegerField(null=True)),
                ('LP_School_Aided', models.IntegerField(null=True)),
                ('LP_School_Un_Aided', models.IntegerField(null=True)),
                ('UP_School_Govt', models.IntegerField(null=True)),
                ('UP_School_LSG', models.IntegerField(null=True)),
                ('UP_School_Aided', models.IntegerField(null=True)),
                ('UP_School_Un_Aided', models.IntegerField(null=True)),
                ('High_School_Govt', models.IntegerField(null=True)),
                ('High_School_LSG', models.IntegerField(null=True)),
                ('High_School_Aided', models.IntegerField(null=True)),
                ('High_School_Un_Aided', models.IntegerField(null=True)),
                ('Higher_Secondary_Govt', models.IntegerField(null=True)),
                ('Higher_Secondary_LSG', models.IntegerField(null=True)),
                ('Higher_Secondary_Aided', models.IntegerField(null=True)),
                ('Higher_Secondary_Un_Aided', models.IntegerField(null=True)),
                ('Vocational_Higher_Secondary_Govt', models.IntegerField(null=True)),
                ('Vocational_Higher_Secondary_LSG', models.IntegerField(null=True)),
                ('Vocational_Higher_Secondary_Aided', models.IntegerField(null=True)),
                ('Vocational_Higher_Secondary_Un_Aided', models.IntegerField(null=True)),
                ('Open_School_Centers_Govt', models.IntegerField(null=True)),
                ('Open_School_Centers_LSG', models.IntegerField(null=True)),
                ('Open_School_Centers_Aided', models.IntegerField(null=True)),
                ('Open_School_Centers_Un_Aided', models.IntegerField(null=True)),
                ('Anganwadi_Centers_Govt', models.IntegerField(null=True)),
                ('Anganwadi_Centers_LSG', models.IntegerField(null=True)),
                ('Anganwadi_Centers_Aided', models.IntegerField(null=True)),
                ('Anganwadi_Centers_Un_Aided', models.IntegerField(null=True)),
                ('Nursery_Pre_Primary_Govt', models.IntegerField(null=True)),
                ('Nursery_Pre_Primary_LSG', models.IntegerField(null=True)),
                ('Nursery_Pre_Primary_Aided', models.IntegerField(null=True)),
                ('Nursery_Pre_Primary_Un_Aided', models.IntegerField(null=True)),
            ],
        ),
    ]
