# Generated by Django 2.0.6 on 2018-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_d010'),
    ]

    operations = [
        migrations.CreateModel(
            name='D011',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Total_NoofSchool', models.IntegerField(null=True)),
                ('Total_Students_M', models.IntegerField(null=True)),
                ('Total_Students_F', models.IntegerField(null=True)),
                ('Total_Student_Transfered_Out', models.IntegerField(null=True)),
                ('Total_Students_Dropout', models.IntegerField(null=True)),
                ('Total_Chronic_Absentees', models.IntegerField(null=True)),
                ('Total_Dropout_SCST', models.IntegerField(null=True)),
                ('Total_CWSN', models.IntegerField(null=True)),
                ('Total_Children_LD', models.IntegerField(null=True)),
                ('Total_CWD', models.IntegerField(null=True)),
            ],
        ),
    ]
