# Generated by Django 2.0.6 on 2018-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_d011'),
    ]

    operations = [
        migrations.CreateModel(
            name='D015',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('No_of_SC_Household', models.IntegerField(null=True)),
                ('No_of_ST_Household', models.IntegerField(null=True)),
                ('Ashraya_Family', models.IntegerField(null=True)),
                ('Single_Room_Household', models.IntegerField(null=True)),
                ('Un_Electrified_Household', models.IntegerField(null=True)),
                ('Household_Without_DrinkingWater', models.IntegerField(null=True)),
                ('Household_Without_Toilet', models.IntegerField(null=True)),
                ('Public_Place_Without_Waste_Disposal', models.IntegerField(null=True)),
                ('Homless_Family', models.IntegerField(null=True)),
                ('Children_Exposed_to_Abuse', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D016',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Under_Orphanges', models.IntegerField(null=True)),
                ('Under_Premetric_Hostel', models.IntegerField(null=True)),
                ('Missing', models.IntegerField(null=True)),
                ('Conflict_with_Law', models.IntegerField(null=True)),
                ('Children_Under_CWC', models.IntegerField(null=True)),
                ('POCSO_Cases', models.IntegerField(null=True)),
                ('At_Risk', models.IntegerField(null=True)),
                ('Adopted', models.IntegerField(null=True)),
                ('Foster_Care_Sponsorship', models.IntegerField(null=True)),
                ('Road_Accidents', models.IntegerField(null=True)),
                ('Calamities', models.IntegerField(null=True)),
                ('Orphant_Children', models.IntegerField(null=True)),
                ('HIV_Effected_Family', models.IntegerField(null=True)),
                ('Migrant_Labours', models.IntegerField(null=True)),
                ('Diability', models.IntegerField(null=True)),
                ('Bedridden', models.IntegerField(null=True)),
                ('Child_Labour', models.IntegerField(null=True)),
                ('Child_Marriage', models.IntegerField(null=True)),
                ('UnWed_Mothers', models.IntegerField(null=True)),
                ('Physical_Punishment', models.IntegerField(null=True)),
            ],
        ),
    ]
