# Generated by Django 2.0.6 on 2018-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_d015_d016'),
    ]

    operations = [
        migrations.CreateModel(
            name='D017',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Balasabha', models.IntegerField(null=True)),
                ('Bala_Panchayat', models.IntegerField(null=True)),
                ('AG_Club', models.IntegerField(null=True)),
                ('AB_Club', models.IntegerField(null=True)),
                ('Children_Gramasabha', models.IntegerField(null=True)),
                ('Working_Group', models.IntegerField(null=True)),
                ('School_Club', models.IntegerField(null=True)),
                ('Vigilance_Committee', models.IntegerField(null=True)),
                ('Social_Audit', models.IntegerField(null=True)),
            ],
        ),
    ]
