# Generated by Django 2.0.6 on 2018-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_d017'),
    ]

    operations = [
        migrations.CreateModel(
            name='D018',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Public_Library', models.IntegerField(null=True)),
                ('Children_Library', models.IntegerField(null=True)),
                ('AG_Club_at_AWC', models.IntegerField(null=True)),
                ('Sports_Arts_Club', models.IntegerField(null=True)),
                ('Cinema_Theatre', models.IntegerField(null=True)),
                ('Cultural_Sports_Centre', models.IntegerField(null=True)),
                ('Community_Hall', models.IntegerField(null=True)),
                ('Children_Park', models.IntegerField(null=True)),
                ('Play_Ground', models.IntegerField(null=True)),
                ('Stadium', models.IntegerField(null=True)),
                ('Swimming_Pool', models.IntegerField(null=True)),
            ],
        ),
    ]
