# Generated by Django 2.0.6 on 2018-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_d018'),
    ]

    operations = [
        migrations.CreateModel(
            name='D019',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Zero_Zone', models.IntegerField(null=True)),
                ('Zebra_Crossing', models.IntegerField(null=True)),
                ('School_Accident_Zone', models.IntegerField(null=True)),
                ('Complaint_Box', models.IntegerField(null=True)),
                ('Vigilance_Committee', models.IntegerField(null=True)),
                ('Child_Friendly_Health_Institution', models.IntegerField(null=True)),
                ('Model_Anganwadi', models.IntegerField(null=True)),
                ('Jagrathasamithi', models.IntegerField(null=True)),
                ('Playground_Upgraded', models.IntegerField(null=True)),
                ('Public_Place_Upgraded', models.IntegerField(null=True)),
                ('Stakeholder_Meeting', models.IntegerField(null=True)),
                ('Public_Private_Coordination', models.IntegerField(null=True)),
                ('Hospital_Development_Committee', models.IntegerField(null=True)),
                ('VHNSC', models.IntegerField(null=True)),
                ('VEC', models.IntegerField(null=True)),
                ('PTA', models.IntegerField(null=True)),
                ('ICDS_Coordination', models.IntegerField(null=True)),
                ('SCST_SubCommittee', models.IntegerField(null=True)),
                ('IEC_Material_Exbited_Vaccination', models.IntegerField(null=True)),
            ],
        ),
    ]
