# Generated by Django 2.0.6 on 2018-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_d013'),
    ]

    operations = [
        migrations.CreateModel(
            name='D014',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Disability_Management_Institution', models.IntegerField(null=True)),
                ('Disability_Management_Govt', models.IntegerField(null=True)),
                ('Disability_Management_LSG', models.IntegerField(null=True)),
                ('Disability_Management_NGO', models.IntegerField(null=True)),
                ('Disability_Management_Private', models.IntegerField(null=True)),
                ('Mental_Health_Institution', models.IntegerField(null=True)),
                ('Mental_Health_Govt', models.IntegerField(null=True)),
                ('Mental_Health_LSG', models.IntegerField(null=True)),
                ('Mental_Health_NGO', models.IntegerField(null=True)),
                ('Mental_Health_Private', models.IntegerField(null=True)),
                ('Special_Education_Institution', models.IntegerField(null=True)),
                ('Special_Education_Govt', models.IntegerField(null=True)),
                ('Special_Education_LSG', models.IntegerField(null=True)),
                ('Special_Education_NGO', models.IntegerField(null=True)),
                ('Special_Education_Private', models.IntegerField(null=True)),
                ('Institutional_Care_Institution', models.IntegerField(null=True)),
                ('Institutional_Care_Govt', models.IntegerField(null=True)),
                ('Institutional_Care_LSG', models.IntegerField(null=True)),
                ('Institutional_Care_NGO', models.IntegerField(null=True)),
                ('Institutional_Care_Private', models.IntegerField(null=True)),
                ('Protection_Services_Institution', models.IntegerField(null=True)),
                ('Protection_Services_Govt', models.IntegerField(null=True)),
                ('Protection_Services_LSG', models.IntegerField(null=True)),
                ('Protection_Services_NGO', models.IntegerField(null=True)),
                ('Protection_Services_Private', models.IntegerField(null=True)),
                ('Scanning_Centre_Institution', models.IntegerField(null=True)),
                ('Scanning_Centre_Govt', models.IntegerField(null=True)),
                ('Scanning_Centre_LSG', models.IntegerField(null=True)),
                ('Scanning_Centre_NGO', models.IntegerField(null=True)),
                ('Scanning_Centre_Private', models.IntegerField(null=True)),
                ('Theraphy_Centre_Institution', models.IntegerField(null=True)),
                ('Theraphy_Centre_Govt', models.IntegerField(null=True)),
                ('Theraphy_Centre_LSG', models.IntegerField(null=True)),
                ('Theraphy_Centre_NGO', models.IntegerField(null=True)),
                ('Theraphy_Centre_Private', models.IntegerField(null=True)),
                ('Palliataive_Care_Institution', models.IntegerField(null=True)),
                ('Palliataive_Care_Govt', models.IntegerField(null=True)),
                ('Palliataive_Care_LSG', models.IntegerField(null=True)),
                ('Palliataive_Care_NGO', models.IntegerField(null=True)),
                ('Palliataive_Care_Private', models.IntegerField(null=True)),
                ('Clinical_Lab_Institution', models.IntegerField(null=True)),
                ('Clinical_Lab_Govt', models.IntegerField(null=True)),
                ('Clinical_Lab_LSG', models.IntegerField(null=True)),
                ('Clinical_Lab_NGO', models.IntegerField(null=True)),
                ('Clinical_Lab_Private', models.IntegerField(null=True)),
                ('Deaddition_Centres_Institution', models.IntegerField(null=True)),
                ('Deaddition_Centres_Govt', models.IntegerField(null=True)),
                ('Deaddition_Centres_LSG', models.IntegerField(null=True)),
                ('Deaddition_Centres_NGO', models.IntegerField(null=True)),
                ('Deaddition_Centres_Private', models.IntegerField(null=True)),
            ],
        ),
    ]
