# Generated by Django 2.0.6 on 2018-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_d014'),
    ]

    operations = [
        migrations.CreateModel(
            name='D012',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('No_of_School', models.IntegerField(null=True)),
                ('Buiding_Permanent', models.IntegerField(null=True)),
                ('Buiding_Temperory', models.IntegerField(null=True)),
                ('Smart_Class_Room', models.IntegerField(null=True)),
                ('Barrier_Free_Status', models.IntegerField(null=True)),
                ('Drinking_Water', models.IntegerField(null=True)),
                ('Toilets', models.IntegerField(null=True)),
                ('Waste_Disposal_Facility', models.IntegerField(null=True)),
                ('Play_Ground_with_STD', models.IntegerField(null=True)),
                ('Kitchen_Permanent', models.IntegerField(null=True)),
                ('Kitchen_Temperory', models.IntegerField(null=True)),
                ('School_With_Green_Initative', models.IntegerField(null=True)),
            ],
        ),
    ]
