# Generated by Django 2.0.6 on 2018-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_d012'),
    ]

    operations = [
        migrations.CreateModel(
            name='D005',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('M_Fully_Immunised', models.IntegerField(null=True)),
                ('F_Fully_Immunised', models.IntegerField(null=True)),
                ('M_Partially_Immunised', models.IntegerField(null=True)),
                ('F_Partially_Immunised', models.IntegerField(null=True)),
                ('M_Incidents_of_Diphtheria', models.IntegerField(null=True)),
                ('F_Incidents_of_Diphtheria', models.IntegerField(null=True)),
                ('M_Woopingcough', models.IntegerField(null=True)),
                ('F_Woopingcough', models.IntegerField(null=True)),
                ('M_Tetnus', models.IntegerField(null=True)),
                ('F_Tetnus', models.IntegerField(null=True)),
                ('M_TB', models.IntegerField(null=True)),
                ('F_TB', models.IntegerField(null=True)),
                ('M_Measelous', models.IntegerField(null=True)),
                ('F_Measelous', models.IntegerField(null=True)),
                ('M_Janundees', models.IntegerField(null=True)),
                ('F_Janundees', models.IntegerField(null=True)),
                ('M_Others', models.IntegerField(null=True)),
                ('F_Others', models.IntegerField(null=True)),
                ('M_Vitamine_A', models.IntegerField(null=True)),
                ('F_Vitamine_A', models.IntegerField(null=True)),
                ('M_IFA', models.IntegerField(null=True)),
                ('F_IFA', models.IntegerField(null=True)),
                ('M_Life_Style_Diesease', models.IntegerField(null=True)),
                ('F_Life_Style_Diesease', models.IntegerField(null=True)),
                ('cancer_M', models.IntegerField(null=True)),
                ('cancer_F', models.IntegerField(null=True)),
                ('CHD_M', models.IntegerField(null=True)),
                ('CHD_F', models.IntegerField(null=True)),
                ('DM_M', models.IntegerField(null=True)),
                ('DM_F', models.IntegerField(null=True)),
                ('BP_M', models.IntegerField(null=True)),
                ('BP_F', models.IntegerField(null=True)),
                ('M_Diaherroea', models.IntegerField(null=True)),
                ('F_Diaherroea', models.IntegerField(null=True)),
                ('M_RTI', models.IntegerField(null=True)),
                ('F_RTI', models.IntegerField(null=True)),
                ('M_Anemia', models.IntegerField(null=True)),
                ('F_Anemia', models.IntegerField(null=True)),
                ('worms_Infected_M', models.IntegerField(null=True)),
                ('worms_Infected_F', models.IntegerField(null=True)),
                ('Emotional_Behavivour_M', models.IntegerField(null=True)),
                ('Emotional_Behavivour_F', models.IntegerField(null=True)),
            ],
        ),
    ]
