# Generated by Django 2.0.6 on 2018-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_d005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d001',
            name='lsgd_jilla_panchayath_ward',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
