# Generated by Django 2.0.6 on 2018-08-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20180817_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='D006',
            fields=[
                ('lsgd_code_and_year', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Preg_Reg_in_Time_G', models.IntegerField(null=True)),
                ('Preg_Reg_in_Time_SC', models.IntegerField(null=True)),
                ('Preg_Reg_in_Time_ST', models.IntegerField(null=True)),
                ('Preg_Reg_not_Time_G', models.IntegerField(null=True)),
                ('Preg_Reg_not_Time_SC', models.IntegerField(null=True)),
                ('Preg_Reg_not_Time_ST', models.IntegerField(null=True)),
                ('JSSY_JSSK_G', models.IntegerField(null=True)),
                ('JSSY_JSSK_SC', models.IntegerField(null=True)),
                ('JSSY_JSSK_ST', models.IntegerField(null=True)),
                ('Birth_Reg_in_Time_G', models.IntegerField(null=True)),
                ('Birth_Reg_in_Time_SC', models.IntegerField(null=True)),
                ('Birth_Reg_in_Time_ST', models.IntegerField(null=True)),
                ('EBF_Mothers_G', models.IntegerField(null=True)),
                ('EBF_Mothers_SC', models.IntegerField(null=True)),
                ('EBF_Mothers_ST', models.IntegerField(null=True)),
                ('IFA_Tablet_G', models.IntegerField(null=True)),
                ('IFA_Tablet_SC', models.IntegerField(null=True)),
                ('IFA_Tablet_ST', models.IntegerField(null=True)),
                ('Risk_Preg_G', models.IntegerField(null=True)),
                ('Risk_Preg_SC', models.IntegerField(null=True)),
                ('Risk_Preg_ST', models.IntegerField(null=True)),
                ('Still_Birth_G', models.IntegerField(null=True)),
                ('Still_Birth_SC', models.IntegerField(null=True)),
                ('Still_Birth_ST', models.IntegerField(null=True)),
                ('Twins_G', models.IntegerField(null=True)),
                ('Twins_SC', models.IntegerField(null=True)),
                ('Twins_ST', models.IntegerField(null=True)),
                ('Institu_Delivery_G', models.IntegerField(null=True)),
                ('Institu_Delivery_SC', models.IntegerField(null=True)),
                ('Institu_Delivery_ST', models.IntegerField(null=True)),
                ('Comple_Maternal_Health_Checkup_G', models.IntegerField(null=True)),
                ('Comple_Maternal_Health_Checkup_SC', models.IntegerField(null=True)),
                ('Comple_Maternal_Health_Checkup_ST', models.IntegerField(null=True)),
                ('Women_SNP_G', models.IntegerField(null=True)),
                ('Women_SNP_SC', models.IntegerField(null=True)),
                ('Women_SNP_ST', models.IntegerField(null=True)),
                ('Maternal_Death_G', models.IntegerField(null=True)),
                ('Maternal_Death_SC', models.IntegerField(null=True)),
                ('Maternal_Death_ST', models.IntegerField(null=True)),
                ('MTP_Abortion_G', models.IntegerField(null=True)),
                ('MTP_Abortion_SC', models.IntegerField(null=True)),
                ('MTP_Abortion_ST', models.IntegerField(null=True)),
                ('Couples_Without_Children_G', models.IntegerField(null=True)),
                ('Couples_Without_Children_SC', models.IntegerField(null=True)),
                ('Couples_Without_Children_ST', models.IntegerField(null=True)),
            ],
        ),
    ]
