# Generated by Django 2.0.6 on 2018-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10, unique=True)),
                ('district_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
