# Generated by Django 2.0.6 on 2018-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsgd', '0002_auto_20180620_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lsgd',
            fields=[
                ('lsgd_code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('lsgd_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
