# Generated by Django 2.0.6 on 2018-07-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsgd', '0004_lsgd_lsgd_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('taluk_code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('taluk_name', models.CharField(max_length=100)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsgd.District')),
            ],
        ),
    ]
