# Generated by Django 2.0.6 on 2018-07-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsgd', '0005_taluk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('block_name', models.CharField(max_length=100)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsgd.District')),
            ],
        ),
        migrations.AddField(
            model_name='lsgd',
            name='lsgd_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.District'),
        ),
        migrations.AddField(
            model_name='lsgd',
            name='lsgd_taluk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.Taluk'),
        ),
        migrations.AddField(
            model_name='lsgd',
            name='lsgd_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.Block'),
        ),
    ]
