# Generated by Django 2.0.6 on 2018-07-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsgd', '0006_auto_20180722_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='district_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.District'),
        ),
        migrations.AlterField(
            model_name='taluk',
            name='district_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.District'),
        ),
    ]
