# Generated by Django 2.0.6 on 2018-07-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsgd', '0008_auto_20180722_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='district_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.District'),
        ),
        migrations.AddField(
            model_name='parliament',
            name='district_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lsgd.District'),
        ),
    ]
